<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-P1L9HPQ" failures="1" tests="2" name="Test(failed)" time="0.102" errors="0" timestamp="2022-06-14T14:03:57 IST">
  <testcase classname="testNGFailtest.fail2" name="Mymethod1" time="0.013">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNGFailtest.fail2.Mymethod1(fail2.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Mymethod1 -->
  <testcase classname="testNGFailtest.fail1" name="Mymethod1" time="0.013"/>
  <testcase classname="testNGFailtest.fail2" name="Mymethod3" time="0.0">
    <ignored/>
  </testcase> <!-- Mymethod3 -->
  <testcase classname="testNGFailtest.fail1" name="Mymethod3" time="0.0">
    <ignored/>
  </testcase> <!-- Mymethod3 -->
  <testcase classname="testNGFailtest.fail1" name="Mymethod2" time="0.0">
    <ignored/>
  </testcase> <!-- Mymethod2 -->
  <testcase classname="testNGFailtest.fail2" name="Mymethod2" time="0.0">
    <ignored/>
  </testcase> <!-- Mymethod2 -->
</testsuite> <!-- Test(failed) -->
